name: Publish cloud-engine on tag

on:
  push:
    tags:
      - 'cloud-engine@*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: Install portable-package deps
        working-directory: portable-package
        run: npm ci
      - name: Sync engine, build and publish
        working-directory: portable-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          node ../scripts/sync-portable.mjs
          npm run build
          npm publish --provenance --access public





