name: Auto bump and tag cloud-engine

on:
  push:
    branches: [ master ]
    paths:
      - 'src/utils/cloud_maker.js'
      - 'src/config/cloudDefaults.json'
      - 'portable-package/**'
      - 'README.md'

jobs:
  version-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Sync portable package
        working-directory: portable-package
        run: node ../scripts/sync-portable.mjs

      - name: Install deps (portable-package)
        working-directory: portable-package
        run: npm ci

      - name: Determine bump type
        id: bump
        run: |
          msg=$(git log -1 --pretty=%B)
          if echo "$msg" | grep -qiE "release:\s*major"; then
            echo "type=major" >> $GITHUB_OUTPUT
          elif echo "$msg" | grep -qiE "release:\s*minor"; then
            echo "type=minor" >> $GITHUB_OUTPUT
          else
            echo "type=patch" >> $GITHUB_OUTPUT
          fi

      - name: Bump version (portable-package)
        working-directory: portable-package
        run: |
          npm version ${{ steps.bump.outputs.type }} --no-git-tag-version
          git add package.json README.md cloudDefaults.json cloud_maker.js
          git commit -m "chore(portable): bump cloud-engine ${{ steps.bump.outputs.type }} [skip ci]" || echo "No changes to commit"

      - name: Create and push tag
        run: |
          ver=$(node -p "require('./portable-package/package.json').version")
          tag="cloud-engine@${ver}"
          # Only create tag if it doesn't exist
          if git rev-parse "$tag" >/dev/null 2>&1; then
            echo "Tag $tag already exists. Skipping tag creation."
          else
            git tag "$tag"
            git push origin "$tag"
          fi


